// Code generated by protoc-gen-go. DO NOT EDIT.
// source: servicepb/service.proto

/*
Package servicepb is a generated protocol buffer package.

It is generated from these files:
	servicepb/service.proto

It has these top-level messages:
	MetadataResponse
	InvokeRequest
	EmptyRequest
	StateRequest
*/
package servicepb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import puppet_datapb "github.com/lyraproj/data-protobuf/datapb"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MetadataResponse struct {
	Typeset     *puppet_datapb.Data `protobuf:"bytes,1,opt,name=typeset" json:"typeset,omitempty"`
	Definitions *puppet_datapb.Data `protobuf:"bytes,2,opt,name=definitions" json:"definitions,omitempty"`
}

func (m *MetadataResponse) Reset()                    { *m = MetadataResponse{} }
func (m *MetadataResponse) String() string            { return proto.CompactTextString(m) }
func (*MetadataResponse) ProtoMessage()               {}
func (*MetadataResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MetadataResponse) GetTypeset() *puppet_datapb.Data {
	if m != nil {
		return m.Typeset
	}
	return nil
}

func (m *MetadataResponse) GetDefinitions() *puppet_datapb.Data {
	if m != nil {
		return m.Definitions
	}
	return nil
}

type InvokeRequest struct {
	Identifier string              `protobuf:"bytes,1,opt,name=identifier" json:"identifier,omitempty"`
	Method     string              `protobuf:"bytes,2,opt,name=method" json:"method,omitempty"`
	Arguments  *puppet_datapb.Data `protobuf:"bytes,3,opt,name=arguments" json:"arguments,omitempty"`
}

func (m *InvokeRequest) Reset()                    { *m = InvokeRequest{} }
func (m *InvokeRequest) String() string            { return proto.CompactTextString(m) }
func (*InvokeRequest) ProtoMessage()               {}
func (*InvokeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *InvokeRequest) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *InvokeRequest) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *InvokeRequest) GetArguments() *puppet_datapb.Data {
	if m != nil {
		return m.Arguments
	}
	return nil
}

type EmptyRequest struct {
}

func (m *EmptyRequest) Reset()                    { *m = EmptyRequest{} }
func (m *EmptyRequest) String() string            { return proto.CompactTextString(m) }
func (*EmptyRequest) ProtoMessage()               {}
func (*EmptyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type StateRequest struct {
	Identifier string              `protobuf:"bytes,1,opt,name=identifier" json:"identifier,omitempty"`
	Parameters *puppet_datapb.Data `protobuf:"bytes,2,opt,name=parameters" json:"parameters,omitempty"`
}

func (m *StateRequest) Reset()                    { *m = StateRequest{} }
func (m *StateRequest) String() string            { return proto.CompactTextString(m) }
func (*StateRequest) ProtoMessage()               {}
func (*StateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *StateRequest) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *StateRequest) GetParameters() *puppet_datapb.Data {
	if m != nil {
		return m.Parameters
	}
	return nil
}

func init() {
	proto.RegisterType((*MetadataResponse)(nil), "puppet.service.MetadataResponse")
	proto.RegisterType((*InvokeRequest)(nil), "puppet.service.InvokeRequest")
	proto.RegisterType((*EmptyRequest)(nil), "puppet.service.EmptyRequest")
	proto.RegisterType((*StateRequest)(nil), "puppet.service.StateRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for DefinitionService service

type DefinitionServiceClient interface {
	Identity(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*puppet_datapb.Data, error)
	Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*puppet_datapb.Data, error)
	Metadata(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*MetadataResponse, error)
	State(ctx context.Context, in *StateRequest, opts ...grpc.CallOption) (*puppet_datapb.Data, error)
}

type definitionServiceClient struct {
	cc *grpc.ClientConn
}

func NewDefinitionServiceClient(cc *grpc.ClientConn) DefinitionServiceClient {
	return &definitionServiceClient{cc}
}

func (c *definitionServiceClient) Identity(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*puppet_datapb.Data, error) {
	out := new(puppet_datapb.Data)
	err := grpc.Invoke(ctx, "/puppet.service.DefinitionService/Identity", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *definitionServiceClient) Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*puppet_datapb.Data, error) {
	out := new(puppet_datapb.Data)
	err := grpc.Invoke(ctx, "/puppet.service.DefinitionService/Invoke", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *definitionServiceClient) Metadata(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*MetadataResponse, error) {
	out := new(MetadataResponse)
	err := grpc.Invoke(ctx, "/puppet.service.DefinitionService/Metadata", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *definitionServiceClient) State(ctx context.Context, in *StateRequest, opts ...grpc.CallOption) (*puppet_datapb.Data, error) {
	out := new(puppet_datapb.Data)
	err := grpc.Invoke(ctx, "/puppet.service.DefinitionService/State", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DefinitionService service

type DefinitionServiceServer interface {
	Identity(context.Context, *EmptyRequest) (*puppet_datapb.Data, error)
	Invoke(context.Context, *InvokeRequest) (*puppet_datapb.Data, error)
	Metadata(context.Context, *EmptyRequest) (*MetadataResponse, error)
	State(context.Context, *StateRequest) (*puppet_datapb.Data, error)
}

func RegisterDefinitionServiceServer(s *grpc.Server, srv DefinitionServiceServer) {
	s.RegisterService(&_DefinitionService_serviceDesc, srv)
}

func _DefinitionService_Identity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DefinitionServiceServer).Identity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/puppet.service.DefinitionService/Identity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DefinitionServiceServer).Identity(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DefinitionService_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DefinitionServiceServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/puppet.service.DefinitionService/Invoke",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DefinitionServiceServer).Invoke(ctx, req.(*InvokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DefinitionService_Metadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DefinitionServiceServer).Metadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/puppet.service.DefinitionService/Metadata",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DefinitionServiceServer).Metadata(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DefinitionService_State_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DefinitionServiceServer).State(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/puppet.service.DefinitionService/State",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DefinitionServiceServer).State(ctx, req.(*StateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DefinitionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "puppet.service.DefinitionService",
	HandlerType: (*DefinitionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Identity",
			Handler:    _DefinitionService_Identity_Handler,
		},
		{
			MethodName: "Invoke",
			Handler:    _DefinitionService_Invoke_Handler,
		},
		{
			MethodName: "Metadata",
			Handler:    _DefinitionService_Metadata_Handler,
		},
		{
			MethodName: "State",
			Handler:    _DefinitionService_State_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "servicepb/service.proto",
}

func init() { proto.RegisterFile("servicepb/service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 347 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x41, 0x4f, 0xf2, 0x40,
	0x10, 0x05, 0xbe, 0xc0, 0x07, 0x03, 0x1f, 0xf9, 0x58, 0x13, 0x25, 0x44, 0x0d, 0xe9, 0x49, 0x0f,
	0x6c, 0x23, 0xc6, 0x9b, 0xd1, 0xc4, 0xe0, 0x81, 0x44, 0x2f, 0xe5, 0xa4, 0xb7, 0x96, 0x0e, 0xb0,
	0xc1, 0xee, 0xae, 0xdd, 0x29, 0x11, 0x7f, 0x8d, 0x3f, 0xd5, 0xd0, 0x16, 0x2c, 0x68, 0xd5, 0x53,
	0xdb, 0xe9, 0x9b, 0xf7, 0xde, 0xbc, 0x19, 0x38, 0x30, 0x18, 0x2e, 0xc4, 0x18, 0xb5, 0x67, 0xa7,
	0x6f, 0x5c, 0x87, 0x8a, 0x14, 0x6b, 0xea, 0x48, 0x6b, 0x24, 0x9e, 0x56, 0x3b, 0x2d, 0xdf, 0x25,
	0x57, 0x7b, 0xf6, 0xea, 0x91, 0x40, 0xac, 0x17, 0xf8, 0x7f, 0x8f, 0xe4, 0xae, 0x2a, 0x0e, 0x1a,
	0xad, 0xa4, 0x41, 0xd6, 0x83, 0xbf, 0xb4, 0xd4, 0x68, 0x90, 0xda, 0xc5, 0x6e, 0xf1, 0xa4, 0xde,
	0xdf, 0xe3, 0x29, 0x51, 0xd2, 0xcf, 0x07, 0x2b, 0xf4, 0x1a, 0xc3, 0x2e, 0xa0, 0xee, 0xe3, 0x44,
	0x48, 0x41, 0x42, 0x49, 0xd3, 0x2e, 0xe5, 0xb7, 0x64, 0x71, 0xd6, 0x2b, 0xfc, 0x1b, 0xca, 0x85,
	0x9a, 0xa3, 0x83, 0xcf, 0x11, 0x1a, 0x62, 0xc7, 0x00, 0xc2, 0x47, 0x49, 0x62, 0x22, 0x30, 0x8c,
	0x95, 0x6b, 0x4e, 0xa6, 0xc2, 0xf6, 0xa1, 0x12, 0x20, 0xcd, 0x94, 0x1f, 0x4b, 0xd4, 0x9c, 0xf4,
	0x8b, 0x9d, 0x41, 0xcd, 0x0d, 0xa7, 0x51, 0x80, 0x92, 0x4c, 0xfb, 0x4f, 0xbe, 0xfa, 0x07, 0xca,
	0x6a, 0x42, 0xe3, 0x36, 0xd0, 0xb4, 0x4c, 0xa5, 0xad, 0x07, 0x68, 0x8c, 0xc8, 0xa5, 0x5f, 0x5b,
	0x39, 0x85, 0xb2, 0x90, 0x3a, 0xa2, 0xef, 0x86, 0x4d, 0x10, 0xfd, 0xb7, 0x12, 0xb4, 0x06, 0x9b,
	0xb1, 0x47, 0xc9, 0x26, 0xd8, 0x35, 0x54, 0x87, 0x31, 0x1d, 0x2d, 0xd9, 0x21, 0xdf, 0x5e, 0x13,
	0xcf, 0x5a, 0xeb, 0x7c, 0xc5, 0x6d, 0x15, 0xd8, 0x15, 0x54, 0x92, 0xf4, 0xd8, 0xd1, 0x6e, 0xfb,
	0x56, 0xaa, 0x79, 0xfd, 0x77, 0x50, 0x5d, 0xef, 0xfd, 0x07, 0x03, 0xdd, 0xdd, 0xbf, 0xbb, 0xf7,
	0x62, 0x15, 0xd8, 0x25, 0x94, 0xe3, 0xfc, 0x3e, 0x53, 0x65, 0x63, 0xcd, 0xf1, 0x72, 0x63, 0x3f,
	0xf6, 0xa6, 0x82, 0x66, 0x91, 0xc7, 0xc7, 0x2a, 0xb0, 0x13, 0xc8, 0x93, 0xeb, 0x19, 0x7b, 0xaa,
	0x7a, 0x29, 0x8f, 0xf1, 0xe7, 0xf6, 0xe6, 0xca, 0xbd, 0x4a, 0x7c, 0xbb, 0xe7, 0xef, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x2f, 0xcf, 0xf2, 0x36, 0xf9, 0x02, 0x00, 0x00,
}
